[project]
name = "tsu-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.9.3",
    "dbt-postgres>=1.9.0",
    "pandas>=2.2.3",
]
